baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme= "PaperMod"

[params]
    mainSections=[]
  author = "Asma Sayed"
  description = "My custom portfolio website."
  # This will link to our custom CSS file later
  

# --- Social Links for the Footer ---
[[params.social]]
  name = "github"
  url = "https://github.com/asmasayed"
[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/" # Add your LinkedIn URL
[[params.social]]
  name = "twitter"
  url = "https://twitter.com/" # Add your Twitter URL

# --- Main Menu Links ---
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2
[[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
